import 'dart:math';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MotivationWidget extends StatelessWidget {
  MotivationWidget({Key? key}) : super(key: key);

  final List<String> _motivationList = [
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "Strive for progress, not perfection. -Unknown",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. -Confucius",
    "You miss 100% of the shots you don’t take. -Wayne Gretzky",
    "The best way to predict the future is to create it. -Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
    "The only way to do great work is to love what you do. -Steve Jobs",
    "Success is not how high you have climbed, but how you make a positive difference to the world. -Roy T. Bennett",
    "Chase your dreams but always know the road that will lead you home again. -Tim McGraw",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. -Chantal Sutherland",
    "Aim for the moon. If you miss, you may hit a star. -W. Clement Stone",
    "If you can dream it, you can achieve it. -Zig Ziglar",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "I have not failed. I’ve just found 10,000 ways that won’t work. -Thomas A. Edison",
    "It’s not about how hard you can hit; it’s about how hard you can get hit and keep moving forward. -Rocky Balboa",
    "Be the change you wish to see in the world. -Mahatma Gandhi",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
    "If you want to achieve greatness, stop asking for permission. -Unknown",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt",
    "Happiness is not something ready-made. It comes from your own actions. -Dalai Lama XIV",
    "Believe in the power of dreams and the magic of hard work. -Unknown",
    "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
    "Believe that you can and you’re halfway there. -Theodore Roosevelt",
    "Success is walking from failure to failure with no loss of enthusiasm. -Winston Churchill",
    "Start where you are. Use what you have. Do what you can. -Arthur Ashe",
    "Happiness is not the absence of problems, it's the ability to deal with them. -Steve Maraboli",
    "Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. -Mary Kay Ash",
    "You cannot swim for new horizons until you have the courage to lose sight of the shore. -William Faulkner",
    "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned",
    "for you? Not much. -Jim Rohn",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. -Zig Ziglar",
    "Our greatest glory is not in never falling, but in rising every time we fall. -Confucius",
    "Success is liking yourself, liking what you do, and liking how you do it. -Maya Angelou",
    "Never give up on something that you can’t go a day without thinking about. -Winston Churchill",
    "If you're not making mistakes, then you're not making decisions. -Catherine Cook",
    "I’ve failed over and over and over again in my life and that is why I succeed. -Michael Jordan",
    "The best way to find yourself is to lose yourself in the service of others. -Mahatma Gandhi",
    "The only place where success comes before work is in the dictionary. -Vidal Sassoon",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "You miss 100 percent of the shots you don’t take. -Wayne Gretzky",
    "Don't let yesterday take up too much of today. -Will Rogers",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston S. Churchill",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
    "Believe you can and you’re halfway there. -Theodore Roosevelt",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. -Winston Churchill",
    "Don’t let yesterday take up too much of today. -Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. -Unknown",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. -Helen Keller",
    "It’s not the years in your life that count. It’s the life in your years. -Abraham Lincoln",
    "Do not go where the path may lead; go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. -Steve Jobs",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. -Chantal Sutherland",
    "The successful warrior is the average man, with laser-like focus. -Bruce Lee",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
    "You can't fall if you don't climb. But there's no joy in living your whole life on the ground. -Unknown",
    "If you don't stand for something, you will fall for anything. -Malcolm X",
    "I have not failed. I've just found 10,000 ways that won't work. -Thomas Edison",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. -Confucius",
    "You miss 100% of the shots you don’t take. -Wayne Gretzky",
    "The best way to predict the future is to create it. -Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
    "The only way to do great work is to love what you do. -Steve Jobs",
    "Success is not how high you have climbed, but how you make a positive difference to the world. -Roy T. Bennett",
    "You can never cross the ocean until you have the courage to lose sight of the shore. -Christopher Columbus",
    "I have not failed. I’ve just found 10,000 ways that won’t work. -Thomas Edison",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. -Zig Ziglar",
    "Our greatest glory is not in never falling, but in rising every time we fall. -Confucius",
    "Success is liking yourself, liking what you do, and liking how you do it. -Maya Angelou",
    "Never give up on something that you can’t go a day without thinking about. -Winston Churchill",
    "If you're not making mistakes, then you're not making decisions. -Catherine Cook",
    "I’ve failed over and over and over again in my life and that is why I succeed. -Michael Jordan",
    "The best way to find yourself is to lose yourself in the service of others. -Mahatma Gandhi",
    "The only place where success comes before work is in the dictionary. -Vidal Sassoon",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "You miss 100 percent of the shots you don’t take. -Wayne Gretzky",
    "Don't let yesterday take up too much of today. -Will Rogers",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston S. Churchill",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
    "Believe you can and you’re halfway there. -Theodore Roosevelt",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. -Winston Churchill",
    "Don’t let yesterday take up too much of today. -Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. -Unknown",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. -Helen Keller",
    "It’s not the years in your life that count. It’s the life in your years. -Abraham Lincoln",
  ];

  @override
  Widget build(BuildContext context) {
    final String motivation =
    _motivationList[Random().nextInt(_motivationList.length)];

    return Padding(
      padding: const EdgeInsets.only(top: 5.0, bottom: 100.0),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.grey[800],
          borderRadius: BorderRadius.circular(25),
        ),
        child: Padding(
          padding: const EdgeInsets.all(15.0),
          child: Text(
            motivation,
            style: const TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.normal,
              color: Colors.white,
            ),
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
